<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile telephone_client1mobiletelephone</name>
   <tag></tag>
   <elementGuidId>5c10ac11-c72b-405c-8b51-3a43c8da2c2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'client1mobiletelephone' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#client1mobiletelephone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e3b6938-2b24-4d95-8807-7546a9d80a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>fa80874f-8976-4b55-90f6-42b2bebda00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1mobiletelephone</value>
      <webElementGuid>1e8c0629-be8a-4b7e-ab6e-d7c601d70097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c836e044-91f0-489d-b661-8489de99898e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-6 form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8162663c-5177-4f22-9935-953744a58846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>de3b9f09-c70c-4937-807a-2ee42a5dd588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1mobiletelephone&quot;)</value>
      <webElementGuid>91918fe2-5bcf-4221-9b59-cc3a6adfc264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client1mobiletelephone' and @type = 'text']</value>
      <webElementGuid>654eacb9-4468-4f18-be13-87e8b5279414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client1mobiletelephone']</value>
      <webElementGuid>bf3f94df-268c-4efd-8845-0f9e46fc4a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div[3]/input</value>
      <webElementGuid>93a4f45f-eb8c-4786-a693-d865d4e93a5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
