<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select titleMrMsMrsMissDrOther</name>
   <tag></tag>
   <elementGuidId>0d1656df-f323-49a2-82a4-050b35965bc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id = 'client1title' and (text() = 'Select titleMrMsMrsMissDrOther' or . = 'Select titleMrMsMrsMissDrOther')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#client1title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b385db7d-d428-42be-9108-99de27b5da7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>e87d078e-38ff-46b1-ab9b-ea697b279cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client1title</value>
      <webElementGuid>74fc3c78-d1d6-4767-89aa-6be9df50026b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ba38b093-1bfa-443a-b603-951738455d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c3c68f8c-ee06-4205-a7d9-2b90b8f1407f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select titleMrMsMrsMissDrOther</value>
      <webElementGuid>68a15a1e-4b52-427e-a0af-6e9a203e31e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client1title&quot;)</value>
      <webElementGuid>0a522cc4-b97d-4839-afa3-f5f754b9a38f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'client1title' and (text() = 'Select titleMrMsMrsMissDrOther' or . = 'Select titleMrMsMrsMissDrOther')]</value>
      <webElementGuid>15ced24a-465a-4b95-87b7-f95c16161f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='client1title']</value>
      <webElementGuid>3e65ff08-f57d-48c2-b6af-d4543cd56bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title*'])[1]/following::select[1]</value>
      <webElementGuid>2664f2a2-b444-4bbb-9c07-fe96113a0453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal information'])[1]/following::select[1]</value>
      <webElementGuid>3cab7233-523e-4d89-9db5-4eb614a25f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name/s*'])[1]/preceding::select[1]</value>
      <webElementGuid>a215ec22-b270-49aa-aaba-9349c21d2c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name*'])[1]/preceding::select[1]</value>
      <webElementGuid>8564c29a-8562-43a9-8e0b-91d1d432ae6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/select</value>
      <webElementGuid>076df5e3-9275-4dcf-98d7-ef755f63c4a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
